# Generated by Django 5.2.5 on 2025-08-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('domaine_dactiviter', models.CharField(blank=True, max_length=100)),
                ('niveau_detude', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('universite_actuel', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('mot_de_passe', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='application.personne')),
            ],
        ),
    ]
